name: Tests
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run tests
        run: swift test

  macos:
    name: macOS tests
    runs-on: macos-15
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.3'
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: SPM tests
        run: make test
      - name: Normalize coverage info
        run: xcrun llvm-cov export -format lcov .build/debug/SourceMapperPackageTests.xctest/Contents/MacOS/SourceMapperPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex "(Test|checkouts)" > coverage.lcov
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.lcov
          verbose: true

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run tests
        run: swift test -v --enable-test-discovery
